/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StaffRole = IDL.Variant({
  'manager' : IDL.Null,
  'owner' : IDL.Null,
  'operator' : IDL.Null,
  'attendant' : IDL.Null,
});
export const FuelType = IDL.Variant({
  'petrol' : IDL.Null,
  'diesel' : IDL.Null,
});
export const Tank = IDL.Record({
  'id' : IDL.Text,
  'threshold' : IDL.Float64,
  'currentVolume' : IDL.Float64,
  'fuelType' : FuelType,
  'capacity' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'staffRole' : IDL.Opt(StaffRole),
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const CashCollection = IDL.Record({
  'id' : IDL.Nat,
  'breakdown' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});
export const ExpenseCategory = IDL.Variant({
  'supplies' : IDL.Null,
  'electricity' : IDL.Null,
  'maintenance' : IDL.Null,
  'salaries' : IDL.Null,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const PriceUpdate = IDL.Record({
  'fuelType' : FuelType,
  'newPrice' : IDL.Float64,
  'effectiveDate' : IDL.Int,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Float64,
  'staffId' : IDL.Principal,
  'rate' : IDL.Float64,
  'fuelType' : FuelType,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Float64,
});
export const ShiftView = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'staffId' : IDL.Principal,
  'endTime' : IDL.Opt(IDL.Int),
  'sales' : IDL.Vec(Sale),
});
export const Staff = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : StaffRole,
  'serialNumber' : IDL.Nat,
  'commissionRate' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const OfflineData = IDL.Record({
  'expenses' : IDL.Vec(Expense),
  'sales' : IDL.Vec(Sale),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStaffMember' : IDL.Func(
      [IDL.Text, IDL.Principal, StaffRole, IDL.Float64],
      [],
      [],
    ),
  'addTank' : IDL.Func([Tank], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'endShift' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCashCollections' : IDL.Func([], [IDL.Vec(CashCollection)], ['query']),
  'getCurrentPrices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(FuelType, IDL.Float64))],
      ['query'],
    ),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getPriceHistory' : IDL.Func([], [IDL.Vec(PriceUpdate)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getSalesAndExpenses' : IDL.Func(
      [],
      [IDL.Vec(Sale), IDL.Vec(Expense)],
      ['query'],
    ),
  'getShifts' : IDL.Func([], [IDL.Vec(ShiftView)], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTanks' : IDL.Func([], [IDL.Vec(Tank)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordCashCollection' : IDL.Func([IDL.Float64, IDL.Text], [], []),
  'recordExpense' : IDL.Func([ExpenseCategory, IDL.Float64, IDL.Text], [], []),
  'recordSale' : IDL.Func(
      [FuelType, IDL.Float64, IDL.Float64, IDL.Principal],
      [],
      [],
    ),
  'removeStaff' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'startShift' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'syncOfflineData' : IDL.Func([OfflineData], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePrice' : IDL.Func([FuelType, IDL.Float64], [], []),
  'updateStaff' : IDL.Func([IDL.Principal, Staff], [], []),
  'updateTankLevel' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StaffRole = IDL.Variant({
    'manager' : IDL.Null,
    'owner' : IDL.Null,
    'operator' : IDL.Null,
    'attendant' : IDL.Null,
  });
  const FuelType = IDL.Variant({ 'petrol' : IDL.Null, 'diesel' : IDL.Null });
  const Tank = IDL.Record({
    'id' : IDL.Text,
    'threshold' : IDL.Float64,
    'currentVolume' : IDL.Float64,
    'fuelType' : FuelType,
    'capacity' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'staffRole' : IDL.Opt(StaffRole),
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const CashCollection = IDL.Record({
    'id' : IDL.Nat,
    'breakdown' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const ExpenseCategory = IDL.Variant({
    'supplies' : IDL.Null,
    'electricity' : IDL.Null,
    'maintenance' : IDL.Null,
    'salaries' : IDL.Null,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const PriceUpdate = IDL.Record({
    'fuelType' : FuelType,
    'newPrice' : IDL.Float64,
    'effectiveDate' : IDL.Int,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Float64,
    'staffId' : IDL.Principal,
    'rate' : IDL.Float64,
    'fuelType' : FuelType,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Float64,
  });
  const ShiftView = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'staffId' : IDL.Principal,
    'endTime' : IDL.Opt(IDL.Int),
    'sales' : IDL.Vec(Sale),
  });
  const Staff = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : StaffRole,
    'serialNumber' : IDL.Nat,
    'commissionRate' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const OfflineData = IDL.Record({
    'expenses' : IDL.Vec(Expense),
    'sales' : IDL.Vec(Sale),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStaffMember' : IDL.Func(
        [IDL.Text, IDL.Principal, StaffRole, IDL.Float64],
        [],
        [],
      ),
    'addTank' : IDL.Func([Tank], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'endShift' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCashCollections' : IDL.Func([], [IDL.Vec(CashCollection)], ['query']),
    'getCurrentPrices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(FuelType, IDL.Float64))],
        ['query'],
      ),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getPriceHistory' : IDL.Func([], [IDL.Vec(PriceUpdate)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getSalesAndExpenses' : IDL.Func(
        [],
        [IDL.Vec(Sale), IDL.Vec(Expense)],
        ['query'],
      ),
    'getShifts' : IDL.Func([], [IDL.Vec(ShiftView)], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTanks' : IDL.Func([], [IDL.Vec(Tank)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordCashCollection' : IDL.Func([IDL.Float64, IDL.Text], [], []),
    'recordExpense' : IDL.Func(
        [ExpenseCategory, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'recordSale' : IDL.Func(
        [FuelType, IDL.Float64, IDL.Float64, IDL.Principal],
        [],
        [],
      ),
    'removeStaff' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'startShift' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'syncOfflineData' : IDL.Func([OfflineData], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePrice' : IDL.Func([FuelType, IDL.Float64], [], []),
    'updateStaff' : IDL.Func([IDL.Principal, Staff], [], []),
    'updateTankLevel' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };