/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CashCollection {
  'id' : bigint,
  'breakdown' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface Expense {
  'id' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'category' : ExpenseCategory,
  'amount' : number,
}
export type ExpenseCategory = { 'supplies' : null } |
  { 'electricity' : null } |
  { 'maintenance' : null } |
  { 'salaries' : null };
export type FuelType = { 'petrol' : null } |
  { 'diesel' : null };
export interface OfflineData {
  'expenses' : Array<Expense>,
  'sales' : Array<Sale>,
}
export interface PriceUpdate {
  'fuelType' : FuelType,
  'newPrice' : number,
  'effectiveDate' : bigint,
}
export interface Sale {
  'id' : bigint,
  'total' : number,
  'staffId' : Principal,
  'rate' : number,
  'endTotalizer' : number,
  'openTotalizer' : number,
  'fuelType' : FuelType,
  'timestamp' : bigint,
  'quantity' : number,
  'saleDate' : bigint,
}
export interface ShiftView {
  'id' : bigint,
  'startTime' : bigint,
  'staffId' : Principal,
  'endTime' : [] | [bigint],
  'sales' : Array<Sale>,
  'shiftDate' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Staff {
  'id' : Principal,
  'name' : string,
  'role' : StaffRole,
  'serialNumber' : bigint,
  'commissionRate' : number,
}
export type StaffRole = { 'manager' : null } |
  { 'owner' : null } |
  { 'operator' : null } |
  { 'attendant' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Tank {
  'id' : string,
  'threshold' : number,
  'currentVolume' : number,
  'fuelType' : FuelType,
  'capacity' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'staffRole' : [] | [StaffRole],
  'name' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStaffMember' : ActorMethod<
    [string, Principal, StaffRole, number],
    undefined
  >,
  'addTank' : ActorMethod<[Tank], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'endShift' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashCollections' : ActorMethod<[], Array<CashCollection>>,
  'getCurrentPrices' : ActorMethod<[], Array<[FuelType, number]>>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getPriceHistory' : ActorMethod<[], Array<PriceUpdate>>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getSalesAndExpenses' : ActorMethod<[], [Array<Sale>, Array<Expense>]>,
  'getShifts' : ActorMethod<[], Array<ShiftView>>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTanks' : ActorMethod<[], Array<Tank>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordCashCollection' : ActorMethod<[number, string], undefined>,
  'recordExpense' : ActorMethod<[ExpenseCategory, number, string], undefined>,
  'recordSale' : ActorMethod<
    [FuelType, number, number, number, number, bigint, Principal],
    undefined
  >,
  'removeStaff' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'startShift' : ActorMethod<[Principal, bigint], bigint>,
  'syncOfflineData' : ActorMethod<[OfflineData], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePrice' : ActorMethod<[FuelType, number], undefined>,
  'updateStaff' : ActorMethod<[Principal, Staff], undefined>,
  'updateTankLevel' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];