/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Tank {
    id: string;
    threshold: number;
    currentVolume: number;
    fuelType: FuelType;
    capacity: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PriceUpdate {
    fuelType: FuelType;
    newPrice: number;
    effectiveDate: bigint;
}
export interface Sale {
    id: bigint;
    total: number;
    staffId: Principal;
    rate: number;
    fuelType: FuelType;
    timestamp: bigint;
    quantity: number;
}
export interface Expense {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: ExpenseCategory;
    amount: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface OfflineData {
    expenses: Array<Expense>;
    sales: Array<Sale>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface CashCollection {
    id: bigint;
    breakdown: string;
    timestamp: bigint;
    amount: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Staff {
    id: Principal;
    name: string;
    role: StaffRole;
    commissionRate: number;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface ShiftView {
    id: bigint;
    startTime: bigint;
    staffId: Principal;
    endTime?: bigint;
    sales: Array<Sale>;
}
export interface UserProfile {
    staffRole?: StaffRole;
    name: string;
    phoneNumber: string;
}
export enum ExpenseCategory {
    supplies = "supplies",
    electricity = "electricity",
    maintenance = "maintenance",
    salaries = "salaries"
}
export enum FuelType {
    petrol = "petrol",
    diesel = "diesel"
}
export enum StaffRole {
    manager = "manager",
    owner = "owner",
    operator = "operator",
    attendant = "attendant"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addStaffMember(staffMember: Staff): Promise<void>;
    addTank(tank: Tank): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    endShift(shiftId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCashCollections(): Promise<Array<CashCollection>>;
    getCurrentPrices(): Promise<Array<[FuelType, number]>>;
    getExpenses(): Promise<Array<Expense>>;
    getPriceHistory(): Promise<Array<PriceUpdate>>;
    getSales(): Promise<Array<Sale>>;
    getSalesAndExpenses(): Promise<[Array<Sale>, Array<Expense>]>;
    getShifts(): Promise<Array<ShiftView>>;
    getStaff(): Promise<Array<Staff>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTanks(): Promise<Array<Tank>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    recordCashCollection(amount: number, breakdown: string): Promise<void>;
    recordExpense(category: ExpenseCategory, amount: number, description: string): Promise<void>;
    recordSale(fuelType: FuelType, quantity: number, rate: number, staffId: Principal): Promise<void>;
    removeStaff(staffId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    startShift(staffId: Principal): Promise<bigint>;
    syncOfflineData(offlineData: OfflineData): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePrice(fuelType: FuelType, newPrice: number): Promise<void>;
    updateStaff(staffId: Principal, staffMember: Staff): Promise<void>;
    updateTankLevel(id: string, volume: number): Promise<void>;
}
import type { Expense as _Expense, ExpenseCategory as _ExpenseCategory, FuelType as _FuelType, OfflineData as _OfflineData, PriceUpdate as _PriceUpdate, Sale as _Sale, ShiftView as _ShiftView, Staff as _Staff, StaffRole as _StaffRole, StripeSessionStatus as _StripeSessionStatus, Tank as _Tank, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addStaffMember(arg0: Staff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffMember(to_candid_Staff_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffMember(to_candid_Staff_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTank(arg0: Tank): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTank(to_candid_Tank_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTank(to_candid_Tank_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async endShift(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endShift(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCashCollections(): Promise<Array<CashCollection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashCollections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashCollections();
            return result;
        }
    }
    async getCurrentPrices(): Promise<Array<[FuelType, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentPrices();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentPrices();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceHistory(): Promise<Array<PriceUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceHistory();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceHistory();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesAndExpenses(): Promise<[Array<Sale>, Array<Expense>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesAndExpenses();
                return [
                    from_candid_vec_n31(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n23(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesAndExpenses();
            return [
                from_candid_vec_n31(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n23(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getShifts(): Promise<Array<ShiftView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShifts();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShifts();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTanks(): Promise<Array<Tank>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTanks();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTanks();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async recordCashCollection(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCashCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCashCollection(arg0, arg1);
            return result;
        }
    }
    async recordExpense(arg0: ExpenseCategory, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordExpense(to_candid_ExpenseCategory_n48(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordExpense(to_candid_ExpenseCategory_n48(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async recordSale(arg0: FuelType, arg1: number, arg2: number, arg3: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSale(to_candid_FuelType_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSale(to_candid_FuelType_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async removeStaff(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStaff(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async startShift(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startShift(arg0);
            return result;
        }
    }
    async syncOfflineData(arg0: OfflineData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.syncOfflineData(to_candid_OfflineData_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncOfflineData(to_candid_OfflineData_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePrice(arg0: FuelType, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrice(to_candid_FuelType_n7(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrice(to_candid_FuelType_n7(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateStaff(arg0: Principal, arg1: Staff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, to_candid_Staff_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, to_candid_Staff_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTankLevel(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTankLevel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTankLevel(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ExpenseCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_FuelType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FuelType): FuelType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PriceUpdate_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceUpdate): PriceUpdate {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Sale_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sale): Sale {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ShiftView_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShiftView): ShiftView {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRole): StaffRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Staff_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Staff): Staff {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Tank_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tank): Tank {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffRole]): StaffRole | null {
    return value.length === 0 ? null : from_candid_StaffRole_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffRole: [] | [_StaffRole];
    name: string;
    phoneNumber: string;
}): {
    staffRole?: StaffRole;
    name: string;
    phoneNumber: string;
} {
    return {
        staffRole: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.staffRole)),
        name: value.name,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: _ExpenseCategory;
    amount: number;
}): {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: ExpenseCategory;
    amount: number;
} {
    return {
        id: value.id,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_ExpenseCategory_n26(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fuelType: _FuelType;
    newPrice: number;
    effectiveDate: bigint;
}): {
    fuelType: FuelType;
    newPrice: number;
    effectiveDate: bigint;
} {
    return {
        fuelType: from_candid_FuelType_n21(_uploadFile, _downloadFile, value.fuelType),
        newPrice: value.newPrice,
        effectiveDate: value.effectiveDate
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    total: number;
    staffId: Principal;
    rate: number;
    fuelType: _FuelType;
    timestamp: bigint;
    quantity: number;
}): {
    id: bigint;
    total: number;
    staffId: Principal;
    rate: number;
    fuelType: FuelType;
    timestamp: bigint;
    quantity: number;
} {
    return {
        id: value.id,
        total: value.total,
        staffId: value.staffId,
        rate: value.rate,
        fuelType: from_candid_FuelType_n21(_uploadFile, _downloadFile, value.fuelType),
        timestamp: value.timestamp,
        quantity: value.quantity
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    staffId: Principal;
    endTime: [] | [bigint];
    sales: Array<_Sale>;
}): {
    id: bigint;
    startTime: bigint;
    staffId: Principal;
    endTime?: bigint;
    sales: Array<Sale>;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        staffId: value.staffId,
        endTime: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.endTime)),
        sales: from_candid_vec_n31(_uploadFile, _downloadFile, value.sales)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _StaffRole;
    commissionRate: number;
}): {
    id: Principal;
    name: string;
    role: StaffRole;
    commissionRate: number;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_StaffRole_n15(_uploadFile, _downloadFile, value.role),
        commissionRate: value.commissionRate
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    threshold: number;
    currentVolume: number;
    fuelType: _FuelType;
    capacity: number;
}): {
    id: string;
    threshold: number;
    currentVolume: number;
    fuelType: FuelType;
    capacity: number;
} {
    return {
        id: value.id,
        threshold: value.threshold,
        currentVolume: value.currentVolume,
        fuelType: from_candid_FuelType_n21(_uploadFile, _downloadFile, value.fuelType),
        capacity: value.capacity
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_FuelType, number]): [FuelType, number] {
    return [
        from_candid_FuelType_n21(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    owner: null;
} | {
    operator: null;
} | {
    attendant: null;
}): StaffRole {
    return "manager" in value ? StaffRole.manager : "owner" in value ? StaffRole.owner : "operator" in value ? StaffRole.operator : "attendant" in value ? StaffRole.attendant : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    petrol: null;
} | {
    diesel: null;
}): FuelType {
    return "petrol" in value ? FuelType.petrol : "diesel" in value ? FuelType.diesel : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supplies: null;
} | {
    electricity: null;
} | {
    maintenance: null;
} | {
    salaries: null;
}): ExpenseCategory {
    return "supplies" in value ? ExpenseCategory.supplies : "electricity" in value ? ExpenseCategory.electricity : "maintenance" in value ? ExpenseCategory.maintenance : "salaries" in value ? ExpenseCategory.salaries : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n43(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_FuelType, number]>): Array<[FuelType, number]> {
    return value.map((x)=>from_candid_tuple_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceUpdate>): Array<PriceUpdate> {
    return value.map((x)=>from_candid_PriceUpdate_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sale>): Array<Sale> {
    return value.map((x)=>from_candid_Sale_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShiftView>): Array<ShiftView> {
    return value.map((x)=>from_candid_ShiftView_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Staff>): Array<Staff> {
    return value.map((x)=>from_candid_Staff_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tank>): Array<Tank> {
    return value.map((x)=>from_candid_Tank_n46(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenseCategory_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Expense_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_FuelType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FuelType): _FuelType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_OfflineData_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfflineData): _OfflineData {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_Sale_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sale): _Sale {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_StaffRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): _StaffRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Staff_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Staff): _Staff {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Tank_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tank): _Tank {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: StaffRole;
    commissionRate: number;
}): {
    id: Principal;
    name: string;
    role: _StaffRole;
    commissionRate: number;
} {
    return {
        id: value.id,
        name: value.name,
        role: to_candid_StaffRole_n3(_uploadFile, _downloadFile, value.role),
        commissionRate: value.commissionRate
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffRole?: StaffRole;
    name: string;
    phoneNumber: string;
}): {
    staffRole: [] | [_StaffRole];
    name: string;
    phoneNumber: string;
} {
    return {
        staffRole: value.staffRole ? candid_some(to_candid_StaffRole_n3(_uploadFile, _downloadFile, value.staffRole)) : candid_none(),
        name: value.name,
        phoneNumber: value.phoneNumber
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expenses: Array<Expense>;
    sales: Array<Sale>;
}): {
    expenses: Array<_Expense>;
    sales: Array<_Sale>;
} {
    return {
        expenses: to_candid_vec_n54(_uploadFile, _downloadFile, value.expenses),
        sales: to_candid_vec_n57(_uploadFile, _downloadFile, value.sales)
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: ExpenseCategory;
    amount: number;
}): {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: _ExpenseCategory;
    amount: number;
} {
    return {
        id: value.id,
        description: value.description,
        timestamp: value.timestamp,
        category: to_candid_ExpenseCategory_n48(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    total: number;
    staffId: Principal;
    rate: number;
    fuelType: FuelType;
    timestamp: bigint;
    quantity: number;
}): {
    id: bigint;
    total: number;
    staffId: Principal;
    rate: number;
    fuelType: _FuelType;
    timestamp: bigint;
    quantity: number;
} {
    return {
        id: value.id,
        total: value.total,
        staffId: value.staffId,
        rate: value.rate,
        fuelType: to_candid_FuelType_n7(_uploadFile, _downloadFile, value.fuelType),
        timestamp: value.timestamp,
        quantity: value.quantity
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    threshold: number;
    currentVolume: number;
    fuelType: FuelType;
    capacity: number;
}): {
    id: string;
    threshold: number;
    currentVolume: number;
    fuelType: _FuelType;
    capacity: number;
} {
    return {
        id: value.id,
        threshold: value.threshold,
        currentVolume: value.currentVolume,
        fuelType: to_candid_FuelType_n7(_uploadFile, _downloadFile, value.fuelType),
        capacity: value.capacity
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): {
    manager: null;
} | {
    owner: null;
} | {
    operator: null;
} | {
    attendant: null;
} {
    return value == StaffRole.manager ? {
        manager: null
    } : value == StaffRole.owner ? {
        owner: null
    } : value == StaffRole.operator ? {
        operator: null
    } : value == StaffRole.attendant ? {
        attendant: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    supplies: null;
} | {
    electricity: null;
} | {
    maintenance: null;
} | {
    salaries: null;
} {
    return value == ExpenseCategory.supplies ? {
        supplies: null
    } : value == ExpenseCategory.electricity ? {
        electricity: null
    } : value == ExpenseCategory.maintenance ? {
        maintenance: null
    } : value == ExpenseCategory.salaries ? {
        salaries: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FuelType): {
    petrol: null;
} | {
    diesel: null;
} {
    return value == FuelType.petrol ? {
        petrol: null
    } : value == FuelType.diesel ? {
        diesel: null
    } : value;
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Expense>): Array<_Expense> {
    return value.map((x)=>to_candid_Expense_n55(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Sale>): Array<_Sale> {
    return value.map((x)=>to_candid_Sale_n58(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
